services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

# _ci-ref-14635

# _ci-ref-86638

# _ci-ref-37772

# _ci-ref-75404

# _ci-ref-36173

# _ci-ref-34931

# _ci-ref-75136

# _ci-ref-28910

# _ci-ref-90960

# _ci-ref-13561

# _ci-ref-93540

# _ci-ref-35929
