services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

# _ci-ref-14635

# _ci-ref-86638

# _ci-ref-37772

# _ci-ref-75404

# _ci-ref-36173

# _ci-ref-34931

# _ci-ref-75136

# _ci-ref-28910

# _ci-ref-90960

# _ci-ref-13561

# _ci-ref-93540

# _ci-ref-35929

# _ci-ref-26457

# _ci-ref-11617

# _ci-ref-13018

# _ci-ref-80070

# _ci-ref-45280

# _ci-ref-82841

# _ci-ref-62837

# _ci-ref-48535

# _ci-ref-71121

# _ci-ref-49968

# _ci-ref-62435

# _ci-ref-70477

# _ci-ref-39928

# _ci-ref-78492

# _ci-ref-38473

# _ci-ref-36978

# _ci-ref-80728
